export let products = [
	{
		id: 1,
		src: 'iphone13.jpg',
		category: 'Phone',
		name: 'Iphone 13',
		price: '1200 $',
		stocked: false,
	},
	{
		id: 2,
		src: 'iphoneXr.jpg',
		category: 'Phone',
		name: 'Iphone XR',
		price: '500 $',
		stocked: true,
	},
	{
		id: 3,
		src: 'samsungs20.jpg',
		category: 'Phone',
		name: 'Samsung s20',
		price: '800 $',
		stocked: false,
	},
	{
		id: 4,
		src: 'mac.jpg',
		category: 'Laptop',
		name: 'MacBook Air',
		price: '1500 $',
		stocked: false,
	},
	{
		id: 5,
		src: 'lenovo.jpg',
		category: 'Laptop',
		name: 'Lenovo Legion',
		price: '1330 $',
		stocked: false,
	},
	{
		id: 6,
		src: 'acer.jpg',
		category: 'Laptop',
		name: 'Acer Aspire',
		price: '999 $',
		stocked: true,
	},
	{
		id: 7,
		src: 'smartBand.jpg',
		category: 'Watch',
		name: 'Smart Band',
		price: '57 $',
		stocked: false,
	},
	{
		id: 8,
		src: 'appleWatch.jpg',
		category: 'Watch',
		name: 'Apple watch',
		price: '120 $',
		stocked: false,
	},
	{
		id: 9,
		src: 'huaweiWatch.jpg',
		category: 'Watch',
		name: 'Huawei Watch',
		price: '170 $',
		stocked: true,
	},
	{
		id: 10,
		src: 'case.jpg',
		category: 'Accessories',
		name: 'Case',
		price: '40 $',
		stocked: true,
	},
	{
		id: 11,
		src: 'charger.jpg',
		category: 'Accessories',
		name: 'Charger',
		price: '35 $',
		stocked: false,
	},
	{
		id: 12,
		src: 'headphones.jpg',
		category: 'Accessories',
		name: 'Headphones',
		price: '350 $',
		stocked: false,
	},
];
